### ISSUE TITLE
Routes Flown Google Map Not Displayed on Pilot Roster Page

### ISSUE THREAD

**Issue by canjar** [Atlasair-Virtual/site#16]
Strange issue, and surely just a bug - when viewing [my roster page](https://crew.atlasair-virtual.com/index.php/profile/view/56) - the Google map at the bottom of the page for **Routes Flown** does not display correctly, and displays only a blank box. I do have the "Hand" icon used for Google Maps, however. 

This is not the case for other pilots Routes Flown maps on the roster, where I can see theirs normally. Essentially, it's the same view of a roster page as if I were not logged in to the site, even though I am. When I am logged out, the view is the same/consistent for all pilots' roster pages - with the blank Routes Flown map box shown. 

Tested in Chrome, Safari, Firefox on macOS 10.15.4, and Chrome on Windows 10 Pro x64.

**Comment by canjar** [comment]
Updating this issue further: the Routes Flown map is now displaying. The behavior was seen while having an outstanding PIREP. Once it was accepted, the map displays correctly. I think this may be the intended functionality (map isn't complete/can't be generated with an outstanding PIREP). If so, this issue may be closed! Thank you!

**Comment by Atlasair-Virtual** [comment]
PIREPs that have not been accepted will no longer attempt to show on the map to fix this issue
